/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.github.kevinip;

import java.util.concurrent.Callable;

import com.github.kevinip.command.CreateFiles;

import picocli.CommandLine;
import picocli.CommandLine.Command;

@Command(
    name = "Lots of files",
    version = { "v1.0" },
    mixinStandardHelpOptions = true,
    subcommands = {
        CreateFiles.class,
    })
public class App implements Callable<Integer> {
    public static void main(String... args) {
        int exitCode = new CommandLine(new App()).execute(args);
        System.exit(exitCode);
    }

    @Override
    public Integer call() throws Exception {
        return 0;
    }
}
