/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.github.kevinip;

import static org.testng.Assert.assertEquals;
import static org.testng.Assert.assertTrue;

import java.io.ByteArrayOutputStream;
import java.io.PrintStream;

import org.mockito.MockitoAnnotations;
import org.testng.annotations.AfterMethod;
import org.testng.annotations.BeforeMethod;
import org.testng.annotations.Test;

import picocli.CommandLine;

public class AppTest {

    final PrintStream originalOut = System.out;
    final PrintStream originalErr = System.err;
    final ByteArrayOutputStream out = new ByteArrayOutputStream();
    final ByteArrayOutputStream err = new ByteArrayOutputStream();

    private App app;

    @BeforeMethod
    public void beforeTest() {
        MockitoAnnotations.initMocks(this);
        app = new App();

        out.reset();
        err.reset();
        System.setOut(new PrintStream(out));
        System.setErr(new PrintStream(err));
    }

    @AfterMethod
    public void afterTest() {
        System.setOut(originalOut);
        System.setErr(originalErr);
    }

    @Test
    public void testApp() {
        // Given
        String[] args = { "-h" };

        CommandLine cmd = new CommandLine(app);

        // When
        final int actual = cmd.execute(args);

        // Then
        assertEquals(0, actual);
        assertTrue(out.toString().contains("Create lots of files"), out.toString());
        assertEquals(err.toString(), "");
    }
}
